### ISSUE TITLE
Unbrowseable Brazilian Portuguese and Simplified Chinese translations

### ISSUE THREAD

**Issue by rffontenelle** [mquinson/po4a-website#17]
Accessing their translations will download the PHP file corresponding to the browsed page (index, documentation, etc.), instead of browsing them.

This happens for Brazilian Portuguese ([português (Brasil)](https://www.po4a.org/index.php.pt_BR)) and Simplified Chinese ([简体中文](https://www.po4a.org/index.php.zh_CN)).

**Comment by rffontenelle** [comment]
Searching around, this seems to be a setting in a Apache Web Server configuration file `httpd.conf`:

```apache
<FilesMatch ".+\.php.(pt_BR|zh_CN|other_languages)$">
    SetHandler application/x-httpd-php
</FilesMatch>
```

where `(pt_BR|zh_CN|other_languages)` contains all valid languages. Alternatively, add all languages, one per [\<FilesMatch>](https://httpd.apache.org/docs/2.4/mod/core.html#filesmatch) directive.

@mquinson Can you please check my suggestion?

**Comment by rffontenelle** [comment]
Considering this explanation, I wonder why does Norwegian (nb_NO) work without issue.

**Comment by duck-rh** [comment]
@rffontenelle I think it works because `nb_NO` is not in the configuration and it falls back to `nb`.

**Comment by mquinson** [comment]
My personal preference is to whatever solution that is easier to apply. If we should just do some `git mv` to use the right names, then that's very good. If it's to update the conf file, then so be it.

@duck-rh tell me what's easier for you.

**Comment by duck-rh** [comment]
I think it would be easier to rename the files and adapt to what Apache, and the browser, are expecting. That means modifying `01-build-pages.sh` and maybe other things.

The Apache configuration we're using can be seen at https://gitlab.com/osci/community-cage-infra-ansible/-/blob/master/data/tenants/po4a/web/mime.conf?ref_type=heads
It comes from the version in Debian because the version in CentOS was outdated, but it's still not perfect, read below.

I realized that some mapping are missing, like zh-Hans and zh-Hant, and I'm going to add them.

As for `sr-Cyrl` it seems it should be called `sr-Cyrl-RS` instead (to be added in the Apache config and to be fixed in the build script).

Moreover file suffixes do not necessarily match the language tag: `pl` is given the `.po` file suffix to avoid clashing with Perl scripts but there are others. It looks like a real mess and I would be tempted to change the config to make them always match.

For the webserver config I prepared these changes: https://gitlab.com/osci/community-cage-infra-ansible/-/merge_requests/681
Could you please have a look and tell me how that looks to all of you? Then if it's OK I'll apply it to the server. There's still need to update the website build script but I've never touched it, could you take take of this part @mquinson ?

**Comment by rffontenelle** [comment]
I wonder if something should be changed on Weblate's side so it still recognize the message catalog of each language.

**Comment by duck-rh** [comment]
I don't know how weblate works but maybe there's a settings to make it follow RFC 3066 (or the obsoleted 1766).

**Comment by duck-rh** [comment]
@mquinson I opened #21 as an alternate proposal for fix. Since we're moving to OpenShift the previous PR on our deployment did no make sense. Also I did not think about using a `.htaccess` file and this is a good idea. The mapping is made to follow your file extensions, disregarding any RFC. If you want to change late then you can simply edit this file to reflect it.

@rffontenelle I just saw your PR and it is somewhat similar to what I made earlier, except on our server instead of the `.htaccess` file, which is a better solution. Your PR unfortunately changes lots of unrelated things. It also creates a container deployment and I just realized that. Anyway this was done slightly differently for the purpose of switching to OpenShift in another PR. If you still think part of your changes are relevant (like the extra tests for example) then maybe you could reopen PRs for that (one for each separate topic please).

**Comment by rffontenelle** [comment]
> @rffontenelle I just saw your PR and it is somewhat similar to what I made earlier, except on our server instead of the `.htaccess` file, which is a better solution. Your PR unfortunately changes lots of unrelated things. It also creates a container deployment and I just realized that. Anyway this was done slightly differently for the purpose of switching to OpenShift in another PR. If you still think part of your changes are relevant (like the extra tests for example) then maybe you could reopen PRs for that (one for each separate topic please).

I suppose you're talking about #19, created by @gemmaro .

**Comment by duck-rh** [comment]
Sorry @rffontenelle I was confused.

**Comment by mquinson** [comment]
I think that this is fixed by a recent PR by @duck-rh, so I'm closing it. Feel free to reopen on need.

**Comment by duck-rh** [comment]
Just to make things clear: it's fixed in the repo but not published yet since the webhook for OpenShift is not set yet. I can force the republishing but I'd rather we finish the setup first.

**Comment by rffontenelle** [comment]
Not published? pt_BR is browseable now.

**Comment by mquinson** [comment]
It's published now. There are other issues remaining, but I guess that this one is gone.
